/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas/index'
import { Route as ServicesSoffitFasciaRouteImport } from './routes/services/soffit-fascia'
import { Route as ServicesRepairRouteImport } from './routes/services/repair'
import { Route as ServicesLeafGuardsRouteImport } from './routes/services/leaf-guards'
import { Route as ServicesInstallationRouteImport } from './routes/services/installation'
import { Route as ServicesCommercialRouteImport } from './routes/services/commercial'
import { Route as ServiceAreasCityRouteImport } from './routes/service-areas/$city'
import { Route as AdminSectionRouteImport } from './routes/admin/section'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as ServiceAreasCityServiceRouteImport } from './routes/service-areas/$city.$service'

const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/service-areas/',
  path: '/service-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSoffitFasciaRoute = ServicesSoffitFasciaRouteImport.update({
  id: '/services/soffit-fascia',
  path: '/services/soffit-fascia',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRepairRoute = ServicesRepairRouteImport.update({
  id: '/services/repair',
  path: '/services/repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLeafGuardsRoute = ServicesLeafGuardsRouteImport.update({
  id: '/services/leaf-guards',
  path: '/services/leaf-guards',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInstallationRoute = ServicesInstallationRouteImport.update({
  id: '/services/installation',
  path: '/services/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCommercialRoute = ServicesCommercialRouteImport.update({
  id: '/services/commercial',
  path: '/services/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasCityRoute = ServiceAreasCityRouteImport.update({
  id: '/service-areas/$city',
  path: '/service-areas/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/section',
  path: '/section',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const ServiceAreasCityServiceRoute = ServiceAreasCityServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => ServiceAreasCityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/section': typeof AdminSectionRoute
  '/service-areas/$city': typeof ServiceAreasCityRouteWithChildren
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/installation': typeof ServicesInstallationRoute
  '/services/leaf-guards': typeof ServicesLeafGuardsRoute
  '/services/repair': typeof ServicesRepairRoute
  '/services/soffit-fascia': typeof ServicesSoffitFasciaRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/service-areas/$city/$service': typeof ServiceAreasCityServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/section': typeof AdminSectionRoute
  '/service-areas/$city': typeof ServiceAreasCityRouteWithChildren
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/installation': typeof ServicesInstallationRoute
  '/services/leaf-guards': typeof ServicesLeafGuardsRoute
  '/services/repair': typeof ServicesRepairRoute
  '/services/soffit-fascia': typeof ServicesSoffitFasciaRoute
  '/service-areas': typeof ServiceAreasIndexRoute
  '/services': typeof ServicesIndexRoute
  '/service-areas/$city/$service': typeof ServiceAreasCityServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/section': typeof AdminSectionRoute
  '/service-areas/$city': typeof ServiceAreasCityRouteWithChildren
  '/services/commercial': typeof ServicesCommercialRoute
  '/services/installation': typeof ServicesInstallationRoute
  '/services/leaf-guards': typeof ServicesLeafGuardsRoute
  '/services/repair': typeof ServicesRepairRoute
  '/services/soffit-fascia': typeof ServicesSoffitFasciaRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/service-areas/$city/$service': typeof ServiceAreasCityServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/gallery'
    | '/admin/gallery'
    | '/admin/section'
    | '/service-areas/$city'
    | '/services/commercial'
    | '/services/installation'
    | '/services/leaf-guards'
    | '/services/repair'
    | '/services/soffit-fascia'
    | '/service-areas/'
    | '/services/'
    | '/service-areas/$city/$service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/gallery'
    | '/admin/gallery'
    | '/admin/section'
    | '/service-areas/$city'
    | '/services/commercial'
    | '/services/installation'
    | '/services/leaf-guards'
    | '/services/repair'
    | '/services/soffit-fascia'
    | '/service-areas'
    | '/services'
    | '/service-areas/$city/$service'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/gallery'
    | '/admin/gallery'
    | '/admin/section'
    | '/service-areas/$city'
    | '/services/commercial'
    | '/services/installation'
    | '/services/leaf-guards'
    | '/services/repair'
    | '/services/soffit-fascia'
    | '/service-areas/'
    | '/services/'
    | '/service-areas/$city/$service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ServiceAreasCityRoute: typeof ServiceAreasCityRouteWithChildren
  ServicesCommercialRoute: typeof ServicesCommercialRoute
  ServicesInstallationRoute: typeof ServicesInstallationRoute
  ServicesLeafGuardsRoute: typeof ServicesLeafGuardsRoute
  ServicesRepairRoute: typeof ServicesRepairRoute
  ServicesSoffitFasciaRoute: typeof ServicesSoffitFasciaRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/service-areas'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/soffit-fascia': {
      id: '/services/soffit-fascia'
      path: '/services/soffit-fascia'
      fullPath: '/services/soffit-fascia'
      preLoaderRoute: typeof ServicesSoffitFasciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/repair': {
      id: '/services/repair'
      path: '/services/repair'
      fullPath: '/services/repair'
      preLoaderRoute: typeof ServicesRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/leaf-guards': {
      id: '/services/leaf-guards'
      path: '/services/leaf-guards'
      fullPath: '/services/leaf-guards'
      preLoaderRoute: typeof ServicesLeafGuardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/installation': {
      id: '/services/installation'
      path: '/services/installation'
      fullPath: '/services/installation'
      preLoaderRoute: typeof ServicesInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/commercial': {
      id: '/services/commercial'
      path: '/services/commercial'
      fullPath: '/services/commercial'
      preLoaderRoute: typeof ServicesCommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/$city': {
      id: '/service-areas/$city'
      path: '/service-areas/$city'
      fullPath: '/service-areas/$city'
      preLoaderRoute: typeof ServiceAreasCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/section': {
      id: '/admin/section'
      path: '/section'
      fullPath: '/admin/section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/service-areas/$city/$service': {
      id: '/service-areas/$city/$service'
      path: '/$service'
      fullPath: '/service-areas/$city/$service'
      preLoaderRoute: typeof ServiceAreasCityServiceRouteImport
      parentRoute: typeof ServiceAreasCityRoute
    }
  }
}

interface AdminRouteChildren {
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminSectionRoute: typeof AdminSectionRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGalleryRoute: AdminGalleryRoute,
  AdminSectionRoute: AdminSectionRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServiceAreasCityRouteChildren {
  ServiceAreasCityServiceRoute: typeof ServiceAreasCityServiceRoute
}

const ServiceAreasCityRouteChildren: ServiceAreasCityRouteChildren = {
  ServiceAreasCityServiceRoute: ServiceAreasCityServiceRoute,
}

const ServiceAreasCityRouteWithChildren =
  ServiceAreasCityRoute._addFileChildren(ServiceAreasCityRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ServiceAreasCityRoute: ServiceAreasCityRouteWithChildren,
  ServicesCommercialRoute: ServicesCommercialRoute,
  ServicesInstallationRoute: ServicesInstallationRoute,
  ServicesLeafGuardsRoute: ServicesLeafGuardsRoute,
  ServicesRepairRoute: ServicesRepairRoute,
  ServicesSoffitFasciaRoute: ServicesSoffitFasciaRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
